name: Report a bug
description: Report something that is broken or incorrect in the pipeline
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Before you post this issue, please check the [Germline-StructuralV-nf README](https://github.com/Sydney-Informatics-Hub/Germline-StructuralV-nf/blob/main/README.md)

  - type: textarea
    id: description
    attributes:
      label: Description of the bug
      description: Please provide a clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: command_used
    attributes:
      label: Command that you ran and terminal output
      description: Steps we can follow to reproduce the behaviour. Please paste the command you used to launch the pipeline and the output printed to your terminal.
      render: console
      placeholder: |
        $ nextflow run main.nf ...

        Some output here 

  - type: textarea
    id: files
    attributes:
      label: Relevant files
      description: |
        Please drag and drop the relevant files here. Create a `.zip` archive if the extension is not allowed.
        Your verbose log file `.nextflow.log` is often useful as well as any custom Nextflow configuration files used.