name: Request a feature
description: Suggest some new functionality be added to the pipeline
labels: enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Description of feature
      description: Please describe your suggestion for a new feature. It will help to describe a problem or use case, plus any alternatives that you have considered.
    validations:
      required: true